LIBIMOBILEDEVICE_GLUE_VERSION = master
LIBIMOBILEDEVICE_GLUE_SITE = https://github.com/libimobiledevice/libimobiledevice-glue/releases/download/1.3.0
LIBIMOBILEDEVICE_GLUE_SOURCE = libimobiledevice-glue-1.3.0.tar.bz2
LIBIMOBILEDEVICE_GLUE_LICENSE = LGPL-2.1
LIBIMOBILEDEVICE_GLUE_LICENSE_FILES = COPYING
LIBIMOBILEDEVICE_GLUE_INSTALL_STAGING = YES
LIBIMOBILEDEVICE_GLUE_DEPENDENCIES = libplist
LIBIMOBILEDEVICE_GLUE_CONF_OPTS = --disable-manpages
LIBIMOBILEDEVICE_AUTORECONF = YES

$(eval $(autotools-package))
